

DESIRED_VELOCITY = "desired_velocity"
WINDOW_SIZE = "window_size"
LOW_OFFSET = "low_offset"
HIGH_OFFSET = "high_offset"
COMMON_ERROR = "common_error"
CHECK_PERIOD = "check_period"
WAYPOINT_RANGE = "waypoint_range"

L_WIN_PARAM_NAMES = [DESIRED_VELOCITY, WINDOW_SIZE, CHECK_PERIOD]
T_WIN_PARAM_NAMES = [
    DESIRED_VELOCITY, LOW_OFFSET, HIGH_OFFSET, COMMON_ERROR]
WAYPOINT_PARAM_NAMES = [DESIRED_VELOCITY, WAYPOINT_RANGE]
WAYPOINTS = "WAYPOINTS"
GPS_POSITION = "GPS_POSITION"

# protocol name들
TAKEOFF = "TAKEOFF"
LAND = "LAND"
VECTOR = "VECTOR"
MISSION_START = "MISSION_START"
EMERGENCY_LANDING = "EMERGENCY_LANDING"
WAYPOINT_REACHED = "WAYPOINT_REACHED"
RUNNING_STATE = "RUNNING_STATE"
# 0: Normal, 1: Time Out, 2: Location Out
